name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: change permissions
        run: exec chmod +x build.sh
      - name: change permissions
        run: exec chmod +x update_electron.sh
      - name: create executable
        id: create-executable
        run: exec npm run package
      - name: upload build
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: run-${{ github.run_number }}
          gzip: folders
          files: >
            ./build/patch-win32-x64.zip
            ./build/patch-darwin-x64.zip
            ./build/patch-linux-x64.zip
