name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: run-${{ github.run_number }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: create executable
        id: create-executable
        run: exec npm run build:linux
      - name: upload build
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: run-${{ github.run_number }}
          files: >
            ./build/patch-win32-x64.zip
            ./build/patch-darwin-x64.zip
            ./build/patch-linux-x64.zip
