name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: change permissions
        run: exec chmod +x build.sh
      - name: change permissions
        run: exec chmod +x update_electron.sh
      - name: set version env variable
        run: |
          VER=$(cat .env)
          echo "PATCH_NAME=$PATCH_NAME" >> $GITHUB_ENV
      - name: create executable
        id: create-executable
        run: exec npm run package
      - name: upload build
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: run-${{ github.run_number }}
          gzip: folders
          files: >
            ./build/${{ env.PATCH_NAME }}-win32-x64.zip
            ./build/${{ env.PATCH_NAME }}-darwin-x64.zip
            ./build/${{ env.PATCH_NAME }}-linux-x64.zip
